import sanat1 from './assets/sanat1.jpg';
import sanat1_2 from './assets/sanat1-2.jpeg';
import salon3 from './assets/salon3.png';

const images = [
    {
      id:1,
      src: sanat1,
      src2: sanat1_2,
      src3: salon3,
      title: ' BU DÜNYANIN KRALLIĞI',
      description: 'Bu ilk resim açıklaması.',
      size: '1920x1080',
      date: '14 EYLÜL 2024',
    },
    {
      id:2,
      src: '/src/assets/resim2.jpeg',
      src2: '/src/assets/resim2-2.jpeg',
      title: 'BU DÜNYANIN KRALLIĞI',
      description: 'Bu ilk resim açıklaması.',
      size: '1920x1080',
      date: '14 EYLÜL 2024',
    },
    {
      id:3,
      src: '/src/assets/resim3.jpeg',
      src2: '/src/assets/resim3-2.jpeg',
      title: 'BU DÜNYANIN KRALLIĞI',
      description: 'Bu ilk resim açıklaması.',
      size: '1920x1080',
      date: '14 EYLÜL 2024',
    },
    {
      id:4,
      src: '/src/assets/resim4.jpeg',
      src2: '/src/assets/resim4-2.jpeg',
      title: 'BU DÜNYANIN KRALLIĞI',
      description: 'Bu ilk resim açıklaması.',
      size: '1920x1080',
      date: '14 EYLÜL 2024',
    },
    {
      id:5,
      src: '/src/assets/resim5.jpeg',
      src2: '/src/assets/resim5-2.jpeg',
      title: 'BU DÜNYANIN KRALLIĞI',
      description: 'Bu ilk resim açıklaması.',
      size: '1920x1080',
      date: '14 EYLÜL 2024',
    },
    {
      id:6,
      src: '/src/assets/resim6.jpeg',
      src2: '/src/assets/resim6-2.jpeg',
      title: 'BU DÜNYANIN KRALLIĞI',
      description: 'Bu ilk resim açıklaması.',
      size: '1920x1080',
      date: '14 EYLÜL 2024',
    },
    {
      id:7,
      src: '/src/assets/resim7.jpeg',
      src2: '/src/assets/resim7-2.jpeg',
      title: 'BU DÜNYANIN KRALLIĞI',
      description: 'Bu ilk resim açıklaması.',
      size: '1920x1080',
      date: '14 EYLÜL 2024',
    },
    {
      id:8,
      src: '/src/assets/sanat8.jpeg',
      src2: '/src/assets/sanat8-2.jpeg',
      title: 'BU DÜNYANIN KRALLIĞI',
      description: 'Bu ilk resim açıklaması.',
      size: '1920x1080',
      date: '14 EYLÜL 2024',
    },
    {
      id:9,
      src: '/src/assets/resim9.jpeg',
      src2: '/src/assets/resim9-2.jpeg',
      title: 'BU DÜNYANIN KRALLIĞI',
      description: 'Bu ilk resim açıklaması.',
      size: '1920x1080',
      date: '14 EYLÜL 2024',
    },
    {
      id:10,
      src: '/src/assets/resim10.jpeg',
      src2: '/src/assets/resim10-2.jpeg',
      title: 'BU DÜNYANIN KRALLIĞI',
      description: 'Bu ilk resim açıklaması.',
      size: '1920x1080',
      date: '14 EYLÜL 2024',
    },
    {
      id:11,
      src: '/src/assets/resim11.jpeg',
      src2: '/src/assets/resim11-2.jpeg',
      title: 'BU DÜNYANIN KRALLIĞI',
      description: 'Bu ilk resim açıklaması.',
      size: '1920x1080',
      date: '14 EYLÜL 2024',
    },
    {
      id:12,
      src: '/src/assets/resim12.jpeg',
      src2: '/src/assets/resim12-2.jpeg',
      title: 'BU DÜNYANIN KRALLIĞI',
      description: 'Bu ilk resim açıklaması.',
      size: '1920x1080',
      date: '14 EYLÜL 2024',
    },
    {
      id:13,
      src: '/src/assets/resim13.jpeg',
      src2: '/src/assets/resim13-2.jpeg',
      title: 'BU DÜNYANIN KRALLIĞI',
      description: 'Bu ilk resim açıklaması.',
      size: '1920x1080',
      date: '14 EYLÜL 2024',
    },
    {
      id:14,
      src: '/src/assets/resim14.jpeg',
      src2: '/src/assets/resim14-2.jpeg',
      title: 'BU DÜNYANIN KRALLIĞI',
      description: 'Bu ilk resim açıklaması.',
      size: '1920x1080',
      date: '14 EYLÜL 2024',
    },
    {
      id:15,
      src: '/src/assets/resim15.jpeg',
      src2: '/src/assets/resim15-2.jpeg',
      title: 'BU DÜNYANIN KRALLIĞI',
      description: 'Bu ilk resim açıklaması.',
      size: '1920x1080',
      date: '14 EYLÜL 2024',
    },
    {
      id:16,
      src: '/src/assets/resim16.jpeg',
      src2: '/src/assets/resim16-2.jpeg',
      title: 'BU DÜNYANIN KRALLIĞI',
      description: 'Bu ilk resim açıklaması.',
      size: '1920x1080',
      date: '14 EYLÜL 2024',
    },
    {
      id:17,
      src: '/src/assets/resim17.jpeg',
      src2: '/src/assets/resim17-2.jpeg',
      title: 'BU DÜNYANIN KRALLIĞI',
      description: 'Bu ilk resim açıklaması.',
      size: '1920x1080',
      date: '14 EYLÜL 2024',
    },
    {
      id:18,
      src: '/src/assets/resim18.jpeg',
      src2: '/src/assets/resim18-2.jpeg',
      title: 'BU DÜNYANIN KRALLIĞI',
      description: 'Bu ilk resim açıklaması.',
      size: '1920x1080',
      date: '14 EYLÜL 2024',
    }
  ];

  export default images;
